package model;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * POJO representing the Report table.
 * Audit log of every report generated by a Manager.
 *
 * reportType values: SALES | INVENTORY | PRICE_CHANGE
 */
public class Report {

    // ----------------------------------------------------------------
    // Fields
    // ----------------------------------------------------------------
    private int           reportId;
    private LocalDateTime generatedDate;
    private String        reportType;       // "SALES" | "INVENTORY" | "PRICE_CHANGE"
    private LocalDate     dateRangeStart;   // nullable
    private LocalDate     dateRangeEnd;     // nullable
    private String        generatedBy;      // FK → UserAccount.userId (Manager)

    // ----------------------------------------------------------------
    // Constructors
    // ----------------------------------------------------------------
    public Report() { }

    public Report(int reportId, LocalDateTime generatedDate, String reportType,
                  LocalDate dateRangeStart, LocalDate dateRangeEnd, String generatedBy) {
        this.reportId       = reportId;
        this.generatedDate  = generatedDate;
        this.reportType     = reportType;
        this.dateRangeStart = dateRangeStart;
        this.dateRangeEnd   = dateRangeEnd;
        this.generatedBy    = generatedBy;
    }

    // ----------------------------------------------------------------
    // Getters & Setters
    // ----------------------------------------------------------------
    public int    getReportId()                              { return reportId; }
    public void   setReportId(int reportId)                 { this.reportId = reportId; }

    public LocalDateTime getGeneratedDate()                            { return generatedDate; }
    public void          setGeneratedDate(LocalDateTime generatedDate) { this.generatedDate = generatedDate; }

    public String getReportType()                            { return reportType; }
    public void   setReportType(String reportType)          { this.reportType = reportType; }

    public LocalDate getDateRangeStart()                           { return dateRangeStart; }
    public void      setDateRangeStart(LocalDate dateRangeStart)   { this.dateRangeStart = dateRangeStart; }

    public LocalDate getDateRangeEnd()                             { return dateRangeEnd; }
    public void      setDateRangeEnd(LocalDate dateRangeEnd)       { this.dateRangeEnd = dateRangeEnd; }

    public String getGeneratedBy()                           { return generatedBy; }
    public void   setGeneratedBy(String generatedBy)        { this.generatedBy = generatedBy; }

    // ----------------------------------------------------------------
    // toString
    // ----------------------------------------------------------------
    @Override
    public String toString() {
        return "Report{" +
               "reportId="          + reportId       +
               ", generatedDate="   + generatedDate  +
               ", reportType='"     + reportType     + '\'' +
               ", dateRangeStart="  + dateRangeStart +
               ", dateRangeEnd="    + dateRangeEnd   +
               ", generatedBy='"    + generatedBy    + '\'' +
               '}';
    }
}
